web/nuremberg/content/urls.py
from django.conf.urls import url, re_path
from .views import ContentView

app_name = 'content'
urlpatterns = [
    re_path(r'^$', ContentView.as_view(template_name='content/landing.html', context={'query': ''}), name="landing"),
    re_path(r'^trials$', ContentView.as_view(template_name='content/trials.html'), name="trials"),
    re_path(r'^approaches$', ContentView.as_view(template_name='content/approaches.html'), name="approaches"),
    re_path(r'^history$', ContentView.as_view(template_name='content/history.html'), name="history"),
    re_path(r'^about$', ContentView.as_view(template_name='content/about.html'), name="about"),

    re_path(r'^people$', ContentView.as_view(template_name='content/people.html'), name="people"),
    re_path(r'^intro$', ContentView.as_view(template_name='content/about.html'), name="intro"),
    re_path(r'^funding$', ContentView.as_view(template_name='content/funding.html'), name="funding"),
    re_path(r'^additional$', ContentView.as_view(template_name='content/history.html'), name="additional"),
    re_path(r'^documents$', ContentView.as_view(template_name='content/documents.html'), name="documents"),
    re_path(r'^nmt_1_intro$', ContentView.as_view(template_name='content/nmt_1_intro.html'), name="nmt_1_intro"),
    re_path(r'^nmt_2_intro$', ContentView.as_view(template_name='content/nmt_2_intro.html'), name="nmt_2_intro"),
    re_path(r'^nmt_3_intro$', ContentView.as_view(template_name='content/nmt_3_intro.html'), name="nmt_3_intro"),
    re_path(r'^nmt_4_intro$', ContentView.as_view(template_name='content/nmt_4_intro.html'), name="nmt_4_intro"),
    re_path(r'^nmt_7_intro$', ContentView.as_view(template_name='content/nmt_7_intro.html'), name="nmt_7_intro")
]

web/nuremberg/core/urls.py
from django.conf import settings
from django.conf.urls import include, url, re_path
from django.contrib import admin
from proxy.views import proxy_view
from django.views.generic.base import RedirectView
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from proxy.views import proxy_view

@csrf_exempt
def proxied(base_url):
    def proxy_handler(request, path):
    	remoteurl = base_url + path
    	return proxy_view(request, remoteurl)
    return proxy_handler

urlpatterns = [
    # re_path(r'^admin/', admin.site.urls),
    re_path(r'^transcripts/', include('nuremberg.transcripts.urls')),
    re_path(r'^documents/', include('nuremberg.documents.urls')),
    re_path(r'^photographs/', include('nuremberg.photographs.urls')),
    re_path(r'^search/', include('nuremberg.search.urls')),
    re_path(r'^', include('nuremberg.content.urls')),
    re_path(r'^proxy_image/printing/(?P<path>.*)$',
        # RedirectView.as_view(url='http://nuremberg.law.harvard.edu/imagedir/HLSL_NUR_printing/%(url)s')),
        proxied(base_url=settings.DOCUMENTS_PRINTING_URL)),
    re_path(r'^proxy_image/(?P<path>.*)$',
        # RedirectView.as_view(url='http://s3.amazonaws.com/nuremberg-documents/%(url)s'))
        proxied(base_url=settings.DOCUMENTS_URL), name='proxy_image'),
    re_path(r'^proxy_transcript/(?P<path>.*)$',
        proxied(base_url=settings.TRANSCRIPTS_URL), name='proxy_transcript'),
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /search/\n\nUser-agent: SiteimproveBot\nDisallow: /\n\nUser-agent: SiteimproveBot-Crawler\nDisallow: /", content_type="text/plain")),
]

handler400 = 'nuremberg.core.views.handler400'
handler403 = 'nuremberg.core.views.handler403'
handler404 = 'nuremberg.core.views.handler404'
handler500 = 'nuremberg.core.views.handler500'

web/nuremberg/search/urls.py
from django.conf.urls import include, url, re_path
from . import views

app_name = 'search'
urlpatterns = [
    # re_path(r'$', views.Search.as_view(), name='search'),
    re_path(r'$', views.Search.as_view(), name='search')
]

web/nuremberg/core/views.py
from django.shortcuts import render

def render_error(request, status, title, friendly_message, friendly_description):
    response = render(request, 'error.html', {'title':title, 'friendly_message': friendly_message, 'friendly_description': friendly_description})
    response.status_code = status
    return response


def handler404(request, exception):
    return render_error(request,
        404,
        'Page Not Found',
        "We can't find the page you're looking for.",
        """
        The page you're trying to access doesn't seem to exist on our site.
        Double check the address to make sure it's correct.
        If you followed a link to this page, you may have to ask the owners
        of that page to update it.
        """
    )

def handler400(request, exception):
    return render_error(request,
        400,
        'Request Error',
        "There's a problem with your request.",
        """
        Your web browser sent us a request that we don't know how to process.
        Make sure your software is up-to-date and try again.
        """
    )
def handler403(request, exception):
    return render_error(request,
        403,
        'Permission Denied',
        "You're not allowed to access that page.",
        """
        The page you're trying to access requires authorization to access.
        If you are authorized, please double-check your login information.
        """
    )

def handler500(request):
    return render_error(request,
        500,
        'Server Error',
        "We had a problem handling your request.",
        """
        Our server encountered an error while finding the page you asked for,
        and had to stop. Sorry about that! We've been notified of the
        error, and we'll see if we can prevent it in the future.
        """
    )

web/nuremberg/core/templates/base.html
{% load compress static compile_static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=360, initial-scale=0.75">

    <title>Nuremberg - {% block title %}Base Page{% endblock %}</title>

    {% compress css %}
      <link type="{% if COMPRESS_ENABLED %}text/less{% else %}text/css{% endif %}" rel="stylesheet" href="{% static 'style/base.less'|compile %}">
    {% endcompress %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="{% static 'scripts/html5shiv.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'scripts/respond.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'scripts/ie8-polyfills.js' %}" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="{% block body_class %}{% endblock %} {% if show_mockup %}mockups{% endif %}">
    <nav aria-labelledby="bypass-link">
      <a class="bypass-link" id="bypass-link" href="#content" tabindex="1">Jump to content</a>
    </nav>
    <header>
      {% block header %}
        {% include 'nav.html' %}
      {% endblock %}
    </header>

    <main>
      {% block content %}
      Nothing here!
      {% endblock %}
    </main>

    <footer class="site-footer">
      {% block footer %}
        {% include "footer.html" %}
      {% endblock %}
    </footer>

    {% block javascript %}
      {# compress all site JS into a single blob #}
      {% compress js %}
        <script src="{% static 'scripts/jquery-1.12.4.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/jquery-ui.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/jquery-ajax-native.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/jquery-mousewheel.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/jquery-imagesloaded.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/spin.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/dropdown.js' %}" type="text/javascript"></script>

        {# jsPDF is as heavy as the rest of our js put together, defer loading until it's needed #}
        {# <script src="{% static 'scripts/jspdf.min.js' %}" type="text/javascript"></script>#}
        <script> window.jsPDFURL = '{% static 'scripts/jspdf.min.js' %}'; </script>

        <script src="{% static 'scripts/modulejs.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/modernizr.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/underscore.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/backbone.min.js' %}" type="text/javascript"></script>

        <script src="{% static 'scripts/search.js' %}" type="text/javascript"></script>

        <script src="{% static 'scripts/transcripts.js' %}" type="text/javascript"></script>

        <script src="{% static 'scripts/download-pdf.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/download-queue.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/document-tools.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/document-viewport.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/images.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/dragging.js' %}" type="text/javascript"></script>
        <script src="{% static 'scripts/documents.js' %}" type="text/javascript"></script>
      {% endcompress %}
      <script>
        $(document).ready(function () {
          var entryPoint = '{% block javascript_module %}{% endblock %}';
          if (entryPoint) {
            modulejs.require(entryPoint);
          }
        });
      </script>
    {% endblock %}
  </body>
</html>

web/nuremberg/core/templates/error.html
{% extends 'base.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
<section class="theme-light">
  <h1>{{friendly_message}}</h1>
  <p>
    {{friendly_description}}
  </p>
  <p>
    Or, try these links instead:
  </p>
  <ul>
    <li> <a href="{% url 'content:landing' %}">Home Page</a>
    <li> <a href="{% url 'search:search' %}">Search the Archive</a>
    <li> <a href="{% url 'content:approaches' %}">Approaches to the Collection</a>
    <li> <a href="{% url 'content:about' %}">About the Project</a>
  </ul>
  <p>
    If you see this message repeatedly, contact us at
    <a href="mailto:specialc@law.harvard.edu" class="email">specialc@law.harvard.edu</a>
    for assistance.
  </p>
</section>
{% endblock %}

web/nuremberg/core/templates/footer.html
<div class="footer-about">
  <div aria-role="heading" class="h3"> Harvard Law School Library Nuremberg Trials Project </div>
  <div>The Nuremberg Trials Project is an open-access initiative to create and present
  digitized images or full-text versions of the Library's Nuremberg documents,
  descriptions of each document, and general information about the trials.
  </div>
  <div>
  <a href="mailto:specialc@law.harvard.edu" class="email">specialc@law.harvard.edu</a>
  </div>
  <div class="copyright">
    Copyright 2020 &copy; The President and Fellows of Harvard College. Last reviewed: March 2020.
  </div>
</div>
<ul class="footer-nav-col offset">
  <li>
    <a href="{% url 'content:about' %}">About the Project </a>
  </li>
  <li>
    <a href="{% url 'content:trials' %}">Trials </a>
  </li>
  <li>
    <a href="{% url 'content:people' %}">People </a>
  </li>
</ul>
<ul class="footer-nav-col">
  <li>
    <a href="{% url 'content:documents' %}">Documents</a>
  </li>
  <li>
    <a href="/search#advanced">Advanced Search</a>
  </li>
  <li>
    <a href="https://accessibility.huit.harvard.edu/digital-accessibility-policy">Accessibility</a>
  </li>
</ul>

web/nuremberg/core/templates/nav.html
<nav class="site-nav" aria-label="Site navigation">
  <div class="site-brand">
    <a class="unstyled" href="{% url 'content:landing' %}">
      <div class="brand-harvard"> Harvard Law School Library </div>
      <div class="brand-harvard-abbr"> HLS </div>
      <div class="brand-project"> Nuremberg Trials Project </div>
    </a>
  </div>
  <ul class="nav-links">
    <li class="has-menu"> <a tabindex="0" role="button" href="#" data-toggle="dropdown"
      {% if request.resolver_match.url_name == 'trials' %}class="active"{% endif %}
      aria-haspopup="true" aria-label="Trials dropdown" > Trials </a>
        <ul class="menu">
          <li><a href="{% url 'content:people' %}">People</a></li>
          <li><a href="{% url 'content:trials' %}">Trials</a></li>
        </ul>
    </li>

    <li> <a href="{% url 'content:documents' %}"
      {% if request.resolver_match.url_name == 'documents' %}class="active"{% endif %}
      >  Documents </a> </li>

    <li class="has-menu"> <a tabindex="0" role="button" href="#" data-toggle="dropdown"
      {% if request.resolver_match.url_name == 'about' %}class="active"{% endif %}
      aria-haspopup="true" aria-label="About dropdown"> About the Project </a>
        <ul class="menu">
          <li><a href="{% url 'content:intro' %}">Intro</a></li>
          <li><a href="{% url 'content:funding' %}">Funding</a></li>
          <li><a href="https://guides.library.harvard.edu/NurembergLibGuide">Guide</a></li>
        </ul>
    </li>
  </ul>
</nav>