web/nuremberg/core/urls.py
from django.conf import settings
from django.conf.urls import include, url, re_path
from django.contrib import admin
from proxy.views import proxy_view
from django.views.generic.base import RedirectView
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from proxy.views import proxy_view

@csrf_exempt
def proxied(base_url):
    def proxy_handler(request, path):
    	remoteurl = base_url + path
    	return proxy_view(request, remoteurl)
    return proxy_handler

urlpatterns = [
    # re_path(r'^admin/', admin.site.urls),
    re_path(r'^transcripts/', include('nuremberg.transcripts.urls')),
    re_path(r'^documents/', include('nuremberg.documents.urls')),
    re_path(r'^photographs/', include('nuremberg.photographs.urls')),
    re_path(r'^search/', include('nuremberg.search.urls')),
    re_path(r'^', include('nuremberg.content.urls')),
    re_path(r'^proxy_image/printing/(?P<path>.*)$',
        # RedirectView.as_view(url='http://nuremberg.law.harvard.edu/imagedir/HLSL_NUR_printing/%(url)s')),
        proxied(base_url=settings.DOCUMENTS_PRINTING_URL)),
    re_path(r'^proxy_image/(?P<path>.*)$',
        # RedirectView.as_view(url='http://s3.amazonaws.com/nuremberg-documents/%(url)s'))
        proxied(base_url=settings.DOCUMENTS_URL), name='proxy_image'),
    re_path(r'^proxy_transcript/(?P<path>.*)$',
        proxied(base_url=settings.TRANSCRIPTS_URL), name='proxy_transcript'),
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /search/\n\nUser-agent: SiteimproveBot\nDisallow: /\n\nUser-agent: SiteimproveBot-Crawler\nDisallow: /", content_type="text/plain")),
]

handler400 = 'nuremberg.core.views.handler400'
handler403 = 'nuremberg.core.views.handler403'
handler404 = 'nuremberg.core.views.handler404'
handler500 = 'nuremberg.core.views.handler500'

web/nuremberg/documents/urls.py
from django.conf.urls import url, re_path
from . import views

app_name = 'documents'
urlpatterns = [
    re_path(r'^(?P<document_id>\d+)-(?P<slug>[-\w]+)?$', views.Show.as_view(), name='show'),
    re_path(r'^(?P<document_id>\d+)[-\w]*$', views.Show.as_view()),
]

web/nuremberg/photographs/urls.py
from django.conf.urls import url, re_path
from . import views

app_name = 'photographs'
urlpatterns = [
    re_path(r'^(?P<photograph_id>\d+)-(?P<slug>[-\w]+)?$', views.Show.as_view(), name='show'),
    re_path(r'^(?P<photograph_id>\d+)[-\w]*$', views.Show.as_view()),
]

web/nuremberg/search/urls.py
from django.conf.urls import include, url, re_path
from . import views

app_name = 'search'
urlpatterns = [
    # re_path(r'$', views.Search.as_view(), name='search'),
    re_path(r'$', views.Search.as_view(), name='search')
]

web/nuremberg/transcripts/urls.py
from django.conf.urls import url, re_path
from . import views

app_name = 'transcripts'
urlpatterns = [
    re_path(r'^(?P<transcript_id>\d+)-(?P<slug>[\-\w]+)?/search$', views.Search.as_view(), name='search'),
    re_path(r'^(?P<transcript_id>\d+)[^/]*/search$', views.Search.as_view()),
    re_path(r'^(?P<transcript_id>\d+)-(?P<slug>[\-\w]+)?$', views.Show.as_view(), name='show'),
    re_path(r'^(?P<transcript_id>\d+)][^/]*$', views.Show.as_view(), name='show'),

]

web/nuremberg/search/forms.py
from haystack.forms import SearchForm, FacetedSearchForm
from haystack.inputs import AutoQuery, Raw
import re
from collections import deque

class EmptyFacetsSearchForm(SearchForm):
    """
    This reimplementation of FacetedSearchForm enables two additional features:

    - filtering by missing facet values (like Date: Unknown)
    - date_year range filtering like 1940-1945, as a search filter
    """
    applied_filters = []
    date_range = [None, None]

    def __init__(self, *args, **kwargs):
        self.facet_to_label = dict(kwargs.pop('facet_to_label'))
        self.selected_facets = kwargs.pop('selected_facets')
        super().__init__(*args, **kwargs)
        if 'year_min' in self.data and 'year_max' in self.data:
            self.selected_facets = [f for f in self.selected_facets if not f.startswith('date_year')]
            self.selected_facets.append('date_year:{}-{}'.format(self.data['year_min'], self.data['year_max']))


    def search(self):
        sqs = super().search()
        self.applied_filters = []
        for facet in self.selected_facets:
            if ":" not in facet:
                continue

            field, value = facet.split(":", 1)

            field_label = self.facet_to_label[field]
            if not field_label:
                continue

            self.applied_filters.append((field_label, value, facet))

            if field == 'date_year' and '-' in value:
                self.date_range = value.split('-', 1)
                sqs = sqs.narrow(u'date_year_exact:[%s TO %s]' % (sqs.query.clean(self.date_range[0]), sqs.query.clean(self.date_range[1])))
                # sqs = sqs.filter(date_year__range=self.date_range)
            else:
                if value == 'None':
                    sqs = sqs.narrow(u'-%s_exact:[* TO *]' % (field))
                elif value:
                    sqs = sqs.narrow(u'%s_exact:"%s"' % (field, sqs.query.clean(value)))

        return sqs

class FieldedSearchForm(SearchForm):
    """
    This form enables natural fielded search with the format:
    general search terms field:field search terms -field:excluded field search terms

    The relevant logic is in `parse_query` and `apply_field_query`.

    The query is parsed into one `auto_query` and many `field_queries`. Each field_query
    is tagged to render whether it is included, excluded, or ignored.

    You can add an additional search field by adding its name to `search_fields`,
    along with the Solr index key if different.


    To enable grouping of TranscriptPage index objects under a single transcript,
    we use an experiment modification to the Haystack Solr Backend. Many search parameters
    are replaced with their group-query equivalents. Be cautious when modifying grouping
    parameters, as the results can be counter-intuitive.

    NOTE: Transcript search results require all keywords to match on a single page.


    Highlighting is used in transcript search results, and as a way to count "occurrences"
    within transcript search.
    """

    auto_query = None
    field_queries = []
    sort_fields = {
        'date-asc': 'date_sort',
        'date-desc': '-date_sort',
        'relevance': '-score',
        'pages-asc': 'total_pages',
        'pages-desc': '-total_pages',
        'page': 'seq_number',
    }

    search_fields = {
        'all': 'text',
        'title': 'title',
        'author': 'authors',
        'authors': True,
        'defendant': 'defendants',
        'defendants': True,
        'hlsl': 'django_id',
        'case': 'case_names',
        'trial': 'case_names',
        'type': 'material_type',
        'date': True,
        'language': True,
        'source': True,
        'evidence': 'evidence_codes',
        'exhibit': 'exhibit_codes',
        'activity': 'trial_activities',
        'activities': 'trial_activities',
        'issue': 'trial_activities',
        'issues': 'trial_activities',
    }
    material_types = ('documents', 'transcripts', 'photographs')

    def __init__(self, *args, **kwargs):
        self.sort_results = kwargs.pop('sort_results')
        self.transcript_id = kwargs.pop('transcript_id', None)

        super().__init__(*args, **kwargs)
        if 'm' in self.data:
            included = self.data.getlist('m')
            self.data = self.data.copy()
            if len(included) < 3:
                self.data['q'] += ' type:{}'.format('|'.join(included))

    def search(self):
        sort = self.sort_fields.get(self.sort_results, 'score')
        sqs = self.searchqueryset

        if self.transcript_id:
            sqs = sqs.filter(material_type='Transcript', transcript_id=self.transcript_id) \
            .order_by(sort)
            # we use snippets to count "occurrences" of a match in transcript search results
            highlight_snippets = 10
        else:
            # we use grouping by document/transcript id to cluster all transcript page results together
            # weirdly it uses a separate sort field
            if sort.startswith('-'):
                sort = sort[1:] + ' desc'
            else:
                sort += ' asc'
            sqs = sqs.group_by('grouping_key', {
                'group.sort': sort + ', seq_number asc',
                'group.limit': 3,
                'sort': sort,
            })
            highlight_snippets = 3

        if not self.is_valid() or not 'q' in self.cleaned_data:
            return sqs

        (self.auto_query, self.field_queries) = self.parse_query_keywords(self.cleaned_data['q'])


        self.highlight_query = ''

        if self.auto_query and not re.match(r'^\s*\*\s*$', self.auto_query):
            sqs = self.apply_field_query(sqs, ['all', self.auto_query])

        for field_query in self.field_queries:
            sqs = self.apply_field_query(sqs, field_query)

        if self.highlight_query:
            sqs = sqs.highlight(**{
                'hl.snippets': highlight_snippets,
                'hl.fragsize':150,
                'hl.q': 'material_type:transcripts AND highlight:({})'.format(AutoQuery(self.highlight_query).prepare(sqs.query)),
                'hl.fl':'highlight',
                'hl.requireFieldMatch':'true',
                'hl.simple.pre':'<mark>',
                'hl.simple.post':'</mark>'
            })

        return sqs

    def parse_query_phrases(self, full_query): # pragma: no cover
        """
        Parser that extracts unmarked phrase queries for fields, eg: date:January 2
        """
        sections = deque(re.split(r'(\-?\w+)\:', full_query))
        auto_query = sections.popleft()
        field_queries = []
        while len(sections) >= 2:
            field_queries.append([sections.popleft(), sections.popleft()])
        return (auto_query, field_queries)

    def parse_query_keywords(self, full_query):
        """
        Parser that extracts single field keyword queries, () keyword groups or "" exact matches
        e.g. date:(January 2)
        """
        sections = re.split(r'((?:\-?\w+)\s*\:\s*(?:"[^"]+"|\([^:]+\)|[\w\-\+\.\|]+))', full_query)
        auto_query = sections[0]
        field_queries = []
        for query in sections[1:]:
            if ':' in query:
                field_queries.append(query.split(':', 1))
            else:
                field_queries.append([None, query])
        return (auto_query, field_queries)

    def apply_field_query(self, sqs, field_query):
        (field, value) = field_query

        if not value or value.isspace():
            return sqs

        if not field:
            field = 'all'

        if field[0] == '-':
            exclude = True
            field = field[1:]
        else:
            exclude = False


        field_key = self.search_fields.get(field)
        if field_key == True:
            field_key = field

        # the solr backend aggressively quotes OR queries,
        # so we must build an OR query manually to keep our loose keyword search
        if field_key:
            values = re.split(r'[|]', value)
            query_list = []
            for value in values:
                if re.match(r'^\s*"?(none|unknown)"?\s*$', value, re.IGNORECASE):
                    query_list.append('(-{}: [* TO *] AND *:*)'.format(field_key))
                else:
                    # to enable snippets for exhibit codes we must add them to the highlight query
                    if field_key in ('exhibit_codes', 'evidence_codes', 'text'):
                        self.highlight_query += ' ' + value
                    # NOTE: field_key is whitelisted above
                    query_list.append('{}:({})'.format(field_key, AutoQuery(value).prepare(sqs.query)))
            raw_query = '({})'.format(' OR '.join(query_list))
            if exclude:
                field_query.append('excluded')
                raw_query = 'NOT {}'.format(raw_query)
            else:
                field_query.append('included')
            sqs = sqs.raw_search(raw_query)
        else:
            field_query.append('ignored')

        return sqs

class DocumentSearchForm(EmptyFacetsSearchForm, FieldedSearchForm):
    pass

web/nuremberg/search/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from haystack.generic_views import SearchView, FacetedSearchView, FacetedSearchMixin
from nuremberg.documents.models import Document
from .forms import DocumentSearchForm
from .lib.digg_paginator import DiggPaginator
from .lib.solr_grouping_backend import GroupedSearchQuerySet

class Search(FacetedSearchView):
    """
    This is a subclass of the default Haystack faceted search view to implement
    our modifications, including pagination, shorter query parameters, custom
    sorting, and labeled facets.

    You can add a search facet to the list simply by placing it in `facet_labels`.

    See `forms.py` for the faceting and fielded search logic itself.
    """
    load_all = False
    queryset = GroupedSearchQuerySet()

    # page numbers like [1, 2 ... 6, 7, 8, 9, 10, ... 19, 20]
    paginator_class = DiggPaginator
    paginate_by = 15
    context_pages = 4
    edge_pages = 2

    form_class = DocumentSearchForm
    search_field = 'q'
    filter_field = 'f'
    material_field = 'm'
    sort_field = 'sort'
    default_sort = 'relevance'

    facet_labels = (
        ('Material Type', 'material_type'),
        ('Trial', 'case_names'),
        ('Defendant', 'defendants'),
        ('Date', 'date_year'),
        ('Author', 'authors'),
        ('Language', 'language'),
        ('Source', 'source'),
        ('Trial Issues', 'trial_activities'),
    )
    facet_to_label = {field: label for (label, field) in facet_labels}
    facet_fields = [label[1] for label in facet_labels]

    def get(self, *args, **kwargs):
        try:
            return super().get(*args, **kwargs)
        except Http404:
            if self.request.GET.get('page', 1) == 1:
                raise
        params = self.request.GET.copy()
        del params['page']
        return redirect('%s?%s' % (self.request.path, params.urlencode()))

    def form_invalid(self, form):
        # override SearchView to give a blank search by default
        # TODO: this seems unnecessary
        self.queryset = form.search()
        context = self.get_context_data(**{
            self.form_name: form,
            'object_list': self.get_queryset()
        })
        return self.render_to_response(context)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'sort_results': self.request.GET.get(self.sort_field, self.default_sort),
            'selected_facets': self.request.GET.getlist(self.filter_field),
            'facet_to_label': self.facet_to_label
        })
        return kwargs

    def get_queryset(self):
        # override FacetedSearchMixin
        qs = super(FacetedSearchMixin, self).get_queryset()
        for field in self.facet_fields:
            sort = 'count'
            qs = qs.facet(field, missing=True, sort=sort, mincount=1)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # pull the query out of form so it is pre-processed
        context['query'] = context['form'].data.get('q') or '*'
        if context['facets']:
            labeled_facets = []
            for (label, field) in self.facet_labels:
                counts = context['facets']['fields'].get(field, [])
                # missing ignores mincount and sorting
                if (None, 0) in counts:
                    counts.remove((None, 0))
                else:
                    pass
                    # sort missing into the other facet values
                    # counts.sort(key=lambda field: field[1], reverse=True)
                labeled_facets.append({
                    'field': field,
                    'label': label,
                    'counts': counts
                })
            context.update({'labeled_facets': labeled_facets})

        if context['form']:
            context['facet_lookup'] = {}
            for (field, value, facet) in context['form'].applied_filters:
                context['facet_lookup'][facet] = True

        if self.request.GET.get('partial'):
            context['base_template'] = 'search/partial.html'
        else:
            context['base_template'] = None

        return context

    def get_paginator(self, *args, **kwargs):
        return self.paginator_class(*args, body=self.context_pages, tail=self.edge_pages, **kwargs)

web/nuremberg/search/templates/search/document-row.html
{% load search_url %}
<tr class="document-row {% if result.authors|length <= 2 %}extra-padding{% endif %}">
  <td>
    <p class="trial-flags">
      <div class="inline-type document-type-icon type-{{result.material_type|slugify}}">
      {{result.material_type}}</div>
      {% for case in result.case_tags %}
        <span class="trial-flag trial-{{case|slugify}}">{{case}}</span>
      {% endfor %}
    </p>
    {% if result.material_type == 'Document' %}
      <a class="unstyled" href="{% url 'documents:show' document_id=result.pk slug=result.slug %}{% if query %}?q={% encode_string query %}{% endif %}">
        <div class="h3">{{result.title}}</div>
        {% if result.literal_title %}
          <p>{{result.literal_title|truncatewords:35|truncatechars:300}}</p>
        {% endif %}

        {% if result.material_type == 'Document' %}
          <p>
            <strong>HLSL Item No.:</strong>
            {{result.pk}}
          </p>
        {% endif %}
      </a>
    {% elif result.material_type == 'Photograph' %}
      <a class="unstyled" href="{% url 'photographs:show' photograph_id=result.pk slug=result.slug %}{% if query %}?q={% encode_string query %}{% endif %}">
        <div class="h3">{{result.title}}</div>
        <p>
          {% if result.highlighted %}
            {% for snippet in result.highlighted.highlight|slice:":1" %}
              <span class="ellipsis">[ ... ]</span>
              {{ snippet|trim_snippet }}
              <span class="ellipsis">[ ... ]</span>
            {% empty %}
              {{result.literal_title|truncatewords:35|truncatechars:300}}
            {% endfor %}
          {% else %}
            {{result.literal_title|truncatewords:35|truncatechars:300}}
          {% endif %}
        </p>
      </a>
    {% elif result.material_type == 'Transcript' %}
      <a class="unstyled" href="{% url 'transcripts:search' transcript_id=result.transcript_id slug=result.slug %}{% if query %}?q={% encode_string query %}{% endif %}">
        <div class="h3">{{result.title}}</div>
        <p>{{group.hits}} result{{ group.hits|pluralize }} in this transcript</p>
        <p class="snippets">
          {% if group.hits == 1 %}
            {% for snippet in result.highlighted.highlight %}
              <span class="ellipsis">[ ... p. {{ result.page_label|default:"unlabeled" }} ]</span>
              {{ snippet|trim_snippet }}
            {% empty %}
              <span class="ellipsis">[ p. {{ result.page_label|default:"unlabeled" }} ]</span>
              {{ result.text|slice:":150"|trim_snippet }}
            {% endfor %}
          {% else %}
            {% for document in group.documents %}
              <span class="ellipsis">[ ... p. {{ document.page_label|default:"unlabeled" }} ]</span>
              {% if document.highlighted %}
                {{ document.highlighted.highlight.0|trim_snippet }}
              {% else %}
                {{ document.text|slice:":150"|trim_snippet }}
              {% endif %}
            {% endfor %}
          {% endif %}
          <span class="ellipsis">[ ... ]</span>
        </p>
      </a>
    {% endif %}

    {% if result.material_type == 'Photograph' %}
      <p>
        <strong>Source:</strong>
        {{result.source}}
      </p>
    {% else %}
      {% comment %}
      <p>
        <strong>Language of Text:</strong>
        {{result.language}}
      </p>
      {% endcomment %}
      {% if result.source %}
        <p>
          <strong>Source of Text:</strong>
          {{result.source}}
        </p>
      {% endif %}
      {% comment %}
      {% if result.trial_activities %}
        <p>
          <strong>Trial Issues:</strong>
          {% for activity in result.trial_activities|slice:":5" %}
              <a href="{% search_query issue=activity %}">{{activity}}</a>{% if not forloop.last %},{% endif %}
          {% endfor %}
          {% if result.trial_activities|length > 5 %}
            ...
          {% endif %}
        </p>
      {% endif %}
      {% endcomment %}
      {% group_merge group.documents 'evidence_codes' as evidence_codes %}
      {% if evidence_codes %}
        <p>
          <strong>Evidence Code{{ evidence_codes|length|pluralize }}{% if result.material_type == 'Transcript' %} Referenced{% endif %}:</strong>
          {% for code in evidence_codes %}
            {{code}}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
      {% endif %}
      {% group_merge group.documents 'exhibit_codes' as exhibit_codes %}
      {% if exhibit_codes %}
        <p>
          <strong>Exhibit Code{{ exhibit_codes|length|pluralize }}{% if result.material_type == 'Transcript' %} Referenced{% endif %}:</strong>
          {% for code in exhibit_codes %}
            {{code}}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
      {% endif %}
      {% comment %}
      {% if result.defendants %}
        <p>
          <strong>Defendant{{result.defendants|pluralize}}:</strong>
          {% for defendant in result.defendants %}
              <a href="{% search_query defendant=defendant %}">{{defendant}}</a>{% if not forloop.last %},{% endif %}
          {% endfor %}
        </p>
      {% endif %}
      {% endcomment %}
    {% endif %}
  </td>
  <td>
    {% if result.material_type == 'Photograph' %}
      <a class="unstyled" href="{% url 'photographs:show' photograph_id=result.pk slug=result.slug %}{% if query %}?q={% encode_string query %}{% endif %}">
        <img src="{{result.thumb_url}}" alt="Thumbnail of a photograph: {{result.literal_title}}" />
      </a>
    {% else %}
      {% for author in result.authors %}
        <p>
          <a href="{% search_query author=author %}">{{author}}</a>
        </p>
      {% endfor %}
    {% endif %}
  </td>
  <td>
    <span class="date">
        {% if result.date %}
          {{result.date}}
        {% else %}
          Unknown
        {% endif %}
      </span>
  </td>
  <td class="type-col">
    <div class="document-type-icon type-{{result.material_type|slugify}}">
    {{result.material_type}}</div>
    {% if result.material_type == 'Document' %}
      <p class="total-pages">{{result.total_pages}} page{{result.total_pages|pluralize}}</p>
    {% endif %}
  </td>
</tr>

web/nuremberg/search/templates/search/pagination.html
{% load search_url %}

{% if paginator.num_pages > 1 %}
  <div class="pagination-row">
    <div class="pagination-controls">
      {% if page_obj.has_previous %}
        <a href="{% result_page page_obj.previous_page_number %}" class="prev-page">Prev</a>
      {% endif %}
      {% for page_number in page_obj.page_range %}
        {% if page_number %}
          <a class="page-number {% if page_number == page_obj.number %}current{% endif %}" href="{% result_page page_number%}">{{page_number}}</a>
        {% else %}
          ...
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a href="{% result_page page_obj.next_page_number %}" class="next-page">Next</a>
      {% endif %}
    </div>
  </div>
{% endif %}

web/nuremberg/search/templates/search/partial.html
{% block content %}
{% endblock %}

web/nuremberg/search/templates/search/search-bar.html
<div class="search-bar-wrapper">
  <div class="search-icon"></div>
  <input type="search" name="q" title="Search query" value="{{ query|default:"" }}" oninvalid="event.preventDefault(); $(this).closest('form').submit()" required />
  <div class="button-wrapper">
    <button class="clear-search" type="reset">Clear</button>
    <button class="button search-button" type="submit">Search</button>
  </div>
</div>

web/nuremberg/search/templates/search/search.html
{% extends base_template|default:"base.html" %}
{% load search_url %}

{% block title %} Document Search Results {% endblock %}

{% block body_class %}document-search{% endblock %}

{% block javascript_module %}search{% endblock %}

{% block content %}
<section role="search" aria-label="Search the archive" class="theme-beige thin">
  <h1 class="h4">Search the archive
    <!-- <a class="h5" tabindex="1" href="#results">Jump to results</a> -->
  </h1>
  <div class="full-width">
    <form class="results-search" role="search" aria-label="full-text search" action='{% url 'search:search' %}' method='GET'>
      {% include 'search/search-bar.html' %}
      <div class="show-advanced-search"><a>Advanced Search</a></div>
    </form>
    {% include 'search/advanced-search-help.html' %}
</section>
<section class="theme-light results">
  <div class="sidebar-layout">
    <div class="sidebar-column search-facets">
      <div class="h4">Filter Results</div>
      {% include 'search/search_facets.html' %}
    </div>
    <div class="main-column search-results" id="results">
      <div class="results-summary">
        <div class="loading-indicator hide">
          Loading results...
        </div>
        <div class="results-count">
          <p class="hint">
            Results {{page_obj.start_index}}-{{page_obj.end_index}} of {{paginator.count}} for
            <strong>
              {{form.auto_query|default:"*"}}
            </strong>

            {% for field_query in form.field_queries %}
              {% if field_query.0 %}
                <span class="field-query {{field_query.2}}">
                  {{field_query.0}}:<strong>{{field_query.1}}</strong>
                </span>
              {% else %}
                <strong>
                  {{field_query.1|default:""}}
                </strong>
              {% endif %}
            {% endfor %}
          </p>
        </div>
        <div class="results-sort">
          <label>
            Sort by
            <select>
              <option value="{% sort_results 'relevance' %}" {% if form.sort_results == 'relevance' %}selected{% endif %}>Relevance</option>
              <option value="{% sort_results 'date-asc' %}" {% if form.sort_results == 'date-asc' %}selected{% endif %}>Earliest Date</option>
              <option value="{% sort_results 'date-desc' %}" {% if form.sort_results == 'date-desc' %}selected{% endif %}>Latest Date</option>
              <option value="{% sort_results 'pages-asc' %}" {% if form.sort_results == 'pages-asc' %}selected{% endif %}>Fewest Pages</option>
              <option value="{% sort_results 'pages-desc' %}" {% if form.sort_results == 'pages-desc' %}selected{% endif %}>Most Pages</option>
            </select>
          </label>
        </div>
      </div>
      <div id="content"></div>
      {% if form.applied_filters %}
        <div class="applied-filters">
          {% for filter in form.applied_filters %}
            <a href="{% remove_facet filter.2 %}" class="applied-filter">
              <strong>{{filter.0}}</strong>
              {{filter.1}}
              <span class="remove-button">&times;</span>
            </a>
          {% endfor %}
          <a href="{% clear_facets %}" class="clear-all"> Clear All Filters </a>
        </div>
      {% endif %}
      {% if paginator.count == 0 %}
        <div class="no-results">
          <p>
            No documents found for your query. Try removing some filters or search terms.
          </p>
        </div>
      {% else %}
        <table>
          <caption>Search results</caption>
          <thead>
            <tr>
              <th class="material-col"> Material </th>
              <th class="author-col"> Authors </th>
              <th> Date </th>
              <th class="type-col"> Type </th>
            </tr>
          </thead>
          <tbody>
            {% for group in page_obj.object_list %}
              {% with group.documents.0 as result %}
                {% include 'search/document-row.html' %}
              {% endwith %}
            {% endfor %}
          </tbody>
        </table>
      {% endif %}
      <div class="spacing" style="height: 20px"></div>
      {% include 'search/pagination.html' %}
    </div>
  </div>
</section>
{% endblock %}