web/nuremberg/content/urls.py
from django.conf.urls import url, re_path
from .views import ContentView

app_name = 'content'
urlpatterns = [
    re_path(r'^$', ContentView.as_view(template_name='content/landing.html', context={'query': ''}), name="landing"),
    re_path(r'^trials$', ContentView.as_view(template_name='content/trials.html'), name="trials"),
    re_path(r'^approaches$', ContentView.as_view(template_name='content/approaches.html'), name="approaches"),
    re_path(r'^history$', ContentView.as_view(template_name='content/history.html'), name="history"),
    re_path(r'^about$', ContentView.as_view(template_name='content/about.html'), name="about"),

    re_path(r'^people$', ContentView.as_view(template_name='content/people.html'), name="people"),
    re_path(r'^intro$', ContentView.as_view(template_name='content/about.html'), name="intro"),
    re_path(r'^funding$', ContentView.as_view(template_name='content/funding.html'), name="funding"),
    re_path(r'^additional$', ContentView.as_view(template_name='content/history.html'), name="additional"),
    re_path(r'^documents$', ContentView.as_view(template_name='content/documents.html'), name="documents"),
    re_path(r'^nmt_1_intro$', ContentView.as_view(template_name='content/nmt_1_intro.html'), name="nmt_1_intro"),
    re_path(r'^nmt_2_intro$', ContentView.as_view(template_name='content/nmt_2_intro.html'), name="nmt_2_intro"),
    re_path(r'^nmt_3_intro$', ContentView.as_view(template_name='content/nmt_3_intro.html'), name="nmt_3_intro"),
    re_path(r'^nmt_4_intro$', ContentView.as_view(template_name='content/nmt_4_intro.html'), name="nmt_4_intro"),
    re_path(r'^nmt_7_intro$', ContentView.as_view(template_name='content/nmt_7_intro.html'), name="nmt_7_intro")
]

web/nuremberg/core/urls.py
from django.conf import settings
from django.conf.urls import include, url, re_path
from django.contrib import admin
from proxy.views import proxy_view
from django.views.generic.base import RedirectView
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from proxy.views import proxy_view

@csrf_exempt
def proxied(base_url):
    def proxy_handler(request, path):
    	remoteurl = base_url + path
    	return proxy_view(request, remoteurl)
    return proxy_handler

urlpatterns = [
    # re_path(r'^admin/', admin.site.urls),
    re_path(r'^transcripts/', include('nuremberg.transcripts.urls')),
    re_path(r'^documents/', include('nuremberg.documents.urls')),
    re_path(r'^photographs/', include('nuremberg.photographs.urls')),
    re_path(r'^search/', include('nuremberg.search.urls')),
    re_path(r'^', include('nuremberg.content.urls')),
    re_path(r'^proxy_image/printing/(?P<path>.*)$',
        # RedirectView.as_view(url='http://nuremberg.law.harvard.edu/imagedir/HLSL_NUR_printing/%(url)s')),
        proxied(base_url=settings.DOCUMENTS_PRINTING_URL)),
    re_path(r'^proxy_image/(?P<path>.*)$',
        # RedirectView.as_view(url='http://s3.amazonaws.com/nuremberg-documents/%(url)s'))
        proxied(base_url=settings.DOCUMENTS_URL), name='proxy_image'),
    re_path(r'^proxy_transcript/(?P<path>.*)$',
        proxied(base_url=settings.TRANSCRIPTS_URL), name='proxy_transcript'),
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /search/\n\nUser-agent: SiteimproveBot\nDisallow: /\n\nUser-agent: SiteimproveBot-Crawler\nDisallow: /", content_type="text/plain")),
]

handler400 = 'nuremberg.core.views.handler400'
handler403 = 'nuremberg.core.views.handler403'
handler404 = 'nuremberg.core.views.handler404'
handler500 = 'nuremberg.core.views.handler500'

web/nuremberg/documents/urls.py
from django.conf.urls import url, re_path
from . import views

app_name = 'documents'
urlpatterns = [
    re_path(r'^(?P<document_id>\d+)-(?P<slug>[-\w]+)?$', views.Show.as_view(), name='show'),
    re_path(r'^(?P<document_id>\d+)[-\w]*$', views.Show.as_view()),
]

web/nuremberg/search/urls.py
from django.conf.urls import include, url, re_path
from . import views

app_name = 'search'
urlpatterns = [
    # re_path(r'$', views.Search.as_view(), name='search'),
    re_path(r'$', views.Search.as_view(), name='search')
]

web/nuremberg/documents/models.py
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from django.db import models
import datetime
import re

global_slug_count = 0

IMAGE_URL_ROOT="http://nuremberg.law.harvard.edu/imagedir/HLSL_NMT01"

class Document(models.Model):
    id = models.AutoField(primary_key=True, db_column='DocID')
    title = models.CharField(max_length=255, db_column='TitleDescriptive')
    literal_title = models.TextField(db_column='Title')
    updated_at = models.DateTimeField(auto_now=True, db_column='Updated')

    image_count = models.IntegerField(db_column='NoOfImages', default=0)

    language = models.ForeignKey('DocumentLanguage', db_column='DocLanguageID', on_delete=models.PROTECT)
    source = models.ForeignKey('DocumentSource', db_column='DocVersionID', on_delete=models.PROTECT)

    def page_range(self):
        return range(1, (self.image_count or 0) + 1)

    def images_screen(self):
        test_empty = self.images.all()
        test_empty = len(test_empty)
        if test_empty:
            return (image for image in self.images.all() if image.scale == DocumentImage.SCREEN)
        else:
            return "no images"

    def date(self):
        date = self.dates.first()
        if date:
            return date.as_date()

    def slug(self): # pragma: no cover
        global global_slug_count
        global_slug_count += 1
        # Try to extract the "genre term" from the descriptive title
        try:
            words = self.title.split(' ')
            n = 4
            while n < len(words) and words[n-1] in ('a', 'an', 'the', 'in', 'of', 'to', 'at', 'on', 'and', 'for'):
                n += 1
            testing =  slugify(' '.join(words[:n]))
            #print ("{0}. DocID: {1} TitleDescriptive slug: {2}".format(global_slug_count, self.id, testing))
            return slugify(' '.join(words[:n]))
        except:
            testing = "descriptive-title-missing"
            #print ("{0}. DocID: {1} TitleDescriptive slug: {2}".format(global_slug_count, self.id, testing))
            return testing

    class Meta:
        managed = False
        db_table = 'tblDoc'

    def __str__(self):
        return "#{0} - {1}".format(self.id, self.title)

class DocumentImage(models.Model):
    document = models.ForeignKey(Document, related_name='images', on_delete=models.PROTECT)

    page_number = models.IntegerField()
    physical_page_number = models.IntegerField(blank=True, null=True)

    THUMB = 't'
    HALF = 'h'
    SCREEN = 's'
    DOUBLE = 'd'
    FULL = 'f'
    IMAGE_SCALES = (
        (THUMB, 'thumb'),
        (HALF, 'half'),
        (SCREEN, 'screen'),
        (DOUBLE, 'double'),
        (FULL, 'full'),
    )

    url = models.CharField(max_length=255, blank=True, null=True)
    scale = models.CharField(max_length=1, choices=IMAGE_SCALES)
    width = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)

    image_type = models.ForeignKey('DocumentImageType', on_delete=models.PROTECT)

    def __getattribute__(self, attrname):
        orig = super().__getattribute__(attrname)
        if attrname == 'url' and settings.PROXY_DOCUMENT_IMAGE_THUMBS and orig and orig.startswith('/static/image_cache/thumb/'):
            return reverse('proxy_image', kwargs={'path': orig.split('/')[-1]})
        return orig

    def find_url(self, scale):
        if self.scale == scale:
            return url
        else:
            images = self.document.images.all()
            filter = (image for image in images if image.page_number == self.page_number and image.scale == scale)
            scaled = next(filter, None)
            if scaled:
                return scaled.url
            else:
                return None

    def thumb_url(self):
        return self.find_url(self.THUMB)
    def screen_url(self):
        return self.find_url(self.SCREEN)
    def full_url(self):
        return self.find_url(self.FULL)

    def image_tag(self):
        return '<a href="{0}"><img src="{0}" alt="Scanned document page {1}" width=100 /></a>'.format(self.url, self.page_number)
    image_tag.allow_tags = True

    def __str__(self):
        return "#{} Page {} {} {}x{}".format(self.document.id, self.page_number, self.scale, self.width, self.height)

    class Meta:
        managed = False
        ordering = ['page_number']


class OldDocumentImage(models.Model):
    id = models.AutoField(primary_key=True, db_column='ImagesListID')
    document = models.ForeignKey(Document, related_name='old_images', on_delete=models.PROTECT, db_column='DocID')

    page_number = models.IntegerField(db_column='PageSequenceNo')
    physical_page_number = models.CharField(max_length=50, db_column='PhysicalPageNo')

    filename = models.CharField(db_column='FileName', max_length=8, blank=True, null=True)

    image_type = models.ForeignKey('DocumentImageType', db_column='PageTypeID', on_delete=models.PROTECT)

    class Meta:
        managed = False
        db_table = 'tblImagesList'


class DocumentImageType(models.Model):
    id = models.AutoField(primary_key=True, db_column='PageTypeID')
    name = models.CharField(max_length=50, db_column='PageType')
    class Meta:
        managed = False
        db_table = 'tblPageTypes'

class DocumentSource(models.Model):
    id = models.AutoField(primary_key=True, db_column='VersionID')
    name = models.CharField(max_length=50, db_column='Version')
    class Meta:
        managed = False
        db_table = 'tblVersions'

class DocumentLanguage(models.Model):
    id = models.AutoField(primary_key=True, db_column='LanguageID')
    name = models.CharField(max_length=15, db_column='Language')
    class Meta:
        managed = False
        db_table = 'tblLanguages'

class DocumentDate(models.Model):
    id = models.AutoField(primary_key=True, db_column='DatesOfDocListID')
    document = models.ForeignKey(Document, related_name='dates', on_delete=models.CASCADE, db_column='DocID')

    day = models.IntegerField(db_column='DocDay')
    month = models.IntegerField(db_column='DocMonthID') # this is technically a foreign key but also just 1-indexed month number
    year = models.IntegerField(db_column='DocYear')

    def as_date(self):
        if not (self.year and self.month and self.day):
            return None
        if self.year == 0 or self.month == 13 or self.day >= 32:
            return None
        if self.month == 2 and self.day == 29 and (self.year % 4) != 0:
            return None # this is an issue
        return datetime.date(self.year, self.month, self.day)

    class Meta:
        managed = False
        db_table = 'tblDatesOfDocList'


class DocumentPersonalAuthor(models.Model):
    id = models.AutoField(primary_key=True, db_column='PersonalAuthorID')
    last_name = models.CharField(max_length=35, db_column='AuthLName')
    first_name = models.CharField(max_length=25, db_column='AuthFName')
    title = models.CharField(max_length=100, db_column='AuthTitle')

    documents = models.ManyToManyField(Document, related_name='personal_authors', through='DocumentsToPersonalAuthors', through_fields=('author', 'document'))

    def full_name(self):
        if self.first_name and self.last_name:
            return '{} {}'.format(self.first_name, self.last_name)
        else:
            return self.first_name or self.last_name or 'Unknown'

    class Meta:
        managed = False
        db_table = 'tblPersonalAuthors'


class DocumentsToPersonalAuthors(models.Model):
    id = models.AutoField(primary_key=True, db_column='PersonalAuthorsListID')
    document = models.ForeignKey(Document, db_column='DocID', on_delete=models.CASCADE)
    author = models.ForeignKey(DocumentPersonalAuthor, db_column='PAuthNameID', on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'tblPersonalAuthorsList'

class DocumentGroupAuthor(models.Model):
    id = models.AutoField(primary_key=True, db_column='GroupAuthorID')
    name = models.CharField(max_length=25, db_column='GroupAuthorName')

    documents = models.ManyToManyField(Document, related_name='group_authors', through='DocumentsToGroupAuthors', through_fields=('author', 'document'))

    def short_name(self):
        return self.name.split(' (')[0]

    class Meta:
        managed = False
        db_table = 'tblGroupAuthors'

class DocumentsToGroupAuthors(models.Model):
    id = models.AutoField(primary_key=True, db_column='GroupAuthorsListID')
    document = models.ForeignKey(Document, db_column='DocID', on_delete=models.CASCADE)
    author = models.ForeignKey(DocumentGroupAuthor, db_column='GANameID', on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'tblGroupAuthorsList'

class DocumentCase(models.Model):
    id = models.AutoField(primary_key=True, db_column='CaseID')
    name = models.CharField(max_length=100, db_column='Case_temp')

    @property
    def tag_name(self):
        # cheating for now
        if self.id == 1:
            return 'IMT'
        elif self.id > 13:
            return 'Other'
        else:
            return 'NMT {}'.format(self.id-1)

    def short_name(self):
        return self.name.split(' -')[0].replace('.', ':').replace(' 0', ' ')

    documents = models.ManyToManyField(Document, related_name='cases', through='DocumentsToCases', through_fields=('case', 'document'))

    class Meta:
        managed = False
        db_table = 'tblCases'


class DocumentsToCases(models.Model):
    id = models.AutoField(primary_key=True, db_column='CasesListID')
    document = models.ForeignKey(Document, db_column='DocID', on_delete=models.CASCADE)
    case = models.ForeignKey(DocumentCase, db_column='DocCaseID', on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'tblCasesList'

class DocumentDefendantManager(models.Manager):
    """
    Filters out null names
    """
    use_for_related_fields = True
    def get_queryset(self):

web/nuremberg/content/views.py
from django.views.generic import TemplateView

class ContentView(TemplateView):
    context = {}
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.context)
        return context

web/nuremberg/documents/views.py
from .models import Document

from django.shortcuts import render
from django.views.generic import View

class Show(View):
    template_name = 'documents/show.html'
    def get(self, request, document_id, *args, **kwargs):
        document = Document.objects \
        .prefetch_related('images') \
        .select_related('language') \
        .select_related('source') \
        .get(id=document_id)

        return render(request, self.template_name,
            {'document': document,
            'query': request.GET.get('q'),
        })

web/nuremberg/content/templates/content/landing.html
{% extends "base.html" %}
{% load static %}

{% block title %} Explore the Nuremberg Trials! {% endblock %}

{% block header %}{% endblock %}

{% block body_class %}landing-page{% endblock %}

{% block content %}
<section class="landing-hero">
  {% include 'nav.html' %}

  <div class="landing-hero-content">
    <hgroup class="landing-header">
      <h1>
        Search thousands of historical documents from the Nuremberg trials.
      </h1>
      <h2>
        Examine trial transcripts, briefs, document books, evidence files, and other
        papers from the trials of military and political leaders of Nazi Germany.
      </h2>
    </hgroup>
    <form class="landing-search" action='{% url 'search:search' %}' method='GET'>
      {% include 'search/search-bar.html' %}

      <fieldset class="include-materials">
        <legend>Include these materials:</legend>
        <label>
          <input type="checkbox" name="m" value="documents" checked />
          Documents
        </label>
        <label>
          <input type="checkbox" name="m" value="transcripts" checked />
          Transcripts
        </label>
        <label>
          <input type="checkbox" name="m" value="photographs" checked />
          Photographs
        </label>
      </fieldset>
    </form>
  </div>
</section>

<section class="collection">
  <div id="content"></div>
  <h2> Access the Collection </h2>
  <p class="partial-width">
    The Harvard Law School Library's Nuremberg Trials Project is an open-access initiative to create
    and present digitized images or full-text versions of the Library's Nuremberg documents,
    descriptions of each document, and general information about the trials.
  </p>
  <p class="hint-serif">
    The Project currently provides access to most of the following materials for five of the
    United States Nuremberg Military Tribunals,
    NMT 1 (U.S.A. v. Karl Brandt et al.),
    NMT 2 (U.S.A. v. Erhard Milch), NMT3 (U.S.A. v. Josef Altstoetter et al.), NMT 4 (U.S.A. v. Pohl et al.), and NMT7 (U.S.A. v. Wilhelm List et al.):
  </p>
  <div class="materials four-column-layout">
    <div class="column material-category material-documents">
      <h3> Trial documents </h3>
      <p class="module">
        Documents used by the prosecution and defense during the trials.
      </p>
    </div>
    <div class="column material-category material-documents">
      <h3> Evidence file documents </h3>
      <p class="module">
        Sets of evidentiary material assembled by the war crimes staff for potential use in the trials.
      </p>
    </div>
    <div class="column material-category material-transcripts">
      <h3> Trial transcripts </h3>
      <p class="module">
        Verbatim records of proceedings in court, including witness testimony, oral arguments, and court rulings and judgments.
      </p>
    </div>
    <div class="column material-category material-photographs">
      <h3> Photographs </h3>
      <p class="module">
        Photographs of Nuremberg Trials defendants, judges, and trial activities.
      </p>
    </div>
  </div>
  <footer>
    <a class="teaser" href="{% url 'content:about' %}"> More about the Project </a>
  </footer>
</section>

<section class="theme-beige approaches">
  <h2> Approaches </h2>
  <div class="three-column-layout approaches-categories">
    <div class="column approach-category">
      <img src="{% static 'images/landing/topics.png' %}" alt="Photograph of Nuremberg courtroom" />
      <h3> Trial Issues </h3>
      <p class="module">
        Uncover the topics related to the Nuremberg trials. Trial issues are criminal activities or subjects
        at issue in a trial that are addressed by a document. Usually these are prosecution
        charges&mdash;like crimes against humanity&mdash;or a defense response. Examine some of the
        collection's most-accessed trial topics.
      </p>

      <p class="tag-list">
        <a class="button tag-button" href="/search/?q=issue%3Aepidemic+jaundice+experiments">Epidemic jaundice experiments</a>
        <a class="button tag-button" href="/search/?q=issue%3Ahigh+altitude+experiments">High altitude experiments</a>
        <a class="button tag-button" href="/search/?q=issue%3Ajewish+skeleton+collection">Jewish skeleton collection</a>
        <a class="button tag-button" href="/search/?q=issue%3Amalaria+experiments">Malaria experiments</a>
        <a class="button tag-button" href="/search/?q=issue%3Apoison+gas+experiments">Poison gas experiments</a>
      </p>
    </div>
    <div class="column approach-category">
      <img src="{% static 'images/landing/people.jpg' %}" alt="Photograph of Hermann Goering and Rudolph Hess reviewing a document at the trial" />
      <h3> People </h3>
      <p class="module">
        Access documents and transcripts related to specific people&mdash;defendants, authors, prosecutors,
        and more&mdash;involved in the trials. Start with these three high-ranking officers.
      </p>
      <ul class="module">
        <li>
          <a href="/search/?q=karl+brandt&m=documents&m=transcripts&m=photographs">Karl Brandt</a>: Reich Commissioner for Health and Sanitation
        </li>
        <li>
          <a href="/search/?q=hermann+goering&m=documents&m=transcripts&m=photographs">Hermann Goering</a>: General of the Air Force, chief of the war economy, Minister for Aviation
        </li>
        <li>
          <a href="/search/?q=heinrich+himmler&m=documents&m=transcripts&m=photographs">Heinrich Himmler</a>: Reichsfuehrer-SS and Chief of the Police
        </li>
      </ul>
    </div>
    <div class="column approach-category">
      <img src="{% static 'images/landing/documents.jpg' %}" alt="A snippet from the header of the typewritten transcript for NMT-1, USA v. Karl Brandt" />
      <h3> Evidence File Documents </h3>
      <p class="module">
        Collections of documents assembled by IMT and NMT staff for possible use in the trials,
        evidence files provided nearly all of the documentary evidence used by the prosecution. The
        documents were organized into sixteen subject groups. Here are a couple of the most interesting.
      </p>
      <ul class="module">
        <li>
          <strong> NO: </strong> <a href="/search/?q=evidence%3Ano*">Nuremberg Organizations</a>  concerning Nazi organizations,
          such as the SS; NMT
        </li>
        <li>
          <strong> NG: </strong> <a href="/search/?q=evidence%3Ang*">Nuremberg Government</a>; concerning Nazi government
          agencies; NMT
        </li>
      </ul>
    </div>
  </div>
  <footer>
    <a class="teaser" href="{% url 'content:people' %}"> More on the people at the trials </a>
  </footer>
</section>

<section class="transcripts">

  <h2> Trial Transcripts </h2>
  <div class="sidebar-layout transcript-preview">
    <div class="sidebar-column transcript-links">
      <a class="unstyled trial-overlay" href="trial">
        <span class="trial-flag trial-nmt-1">NMT 1</span>
        <img src="{% static 'images/landing/trial-transcripts.jpg' %}" alt="A snippet from the header of the typewritten transcript for NMT-1, USA v. Karl Brandt" />
      </a>
      <h3> NMT Case 1 <br /> USA v. Karl Brandt et al. 1946-47 </h3>
      <nav class="sub-nav vertical" aria-label="Information about NMT-1">
        <li>
          <a href="{% url 'content:nmt_1_intro' %}">Table of Contents</a>
        </li>
        <li>
          <a href="{% url 'content:nmt_1_intro' %}">Detailed Summary</a>
        </li>
      </nav>
    </div>
    <div class="main-column transcript-summary">
      <blockquote>
        Whatever book or treatise on medical ethics we may
        examine, and whatever expert on forensic medicine we
        may question, will say that it is a fundamental and
        inescapable obligation of every physician under any
        known system of law not to perform a dangerous
        experiment without the subject's consent.
      </blockquote>
      <cite>
        Telford Taylor, Chief of Counsel for war crimes for all NMT trials, NMT 1 transcript, 9 December 1946
      </cite>
      <p>
        Currently, we have been able to make available the full, keyword-searchable text of four trial transcripts, documenting the verbatim daily proceedings of NMT Trials 1, 2, 3 and 7, ranging in extent from 4,000 to 12,000 pages each. They include
        witness testimony, the presentation of exhibits, oral arguments by
        counsel, and rulings by the tribunal.
      </p>
      <footer>
        <a class="teaser" href="/transcripts/1-transcript-for-nmt-1-medical-case?seq=1&q=+type:transcripts"> Begin reading </a>
      </footer>
    </div>
  </div>
</section>

<section class="progress theme-blue">
  <h2> Project Progress </h2>
  <div class="project-progress sidebar-layout">

    <div class="progress-summary sidebar-column">
      <p>As of fall 2016, we have digitized images of all 650,000 pages of documents and transcripts in the collection
     and have provided searchable text for 5 of the 13 transcripts using
     corrected OCR.</p>

      <p>We have completed full document analysis -- and created searchable metadata for -- the document collections of 5 of the 13 trials.</p>

    </div>

    <div class="progress-graph main-column">
      <div class="progress-bar">
        <div class="bar-segment documents-digitized" style="width: 100%;">100%</div>
      </div>
      <div class="progress-legend">
        Documents and Transcripts Digitized
      </div>
    </div>

    <div class="progress-graph main-column">
      <div class="progress-bar">
        <div class="bar-segment transcripts-keyed" style="width: 30%;">30%</div>
      </div>
      <div class="progress-legend">
        Transcripts OCR-corrected
      </div>
    </div>

    <div class="progress-graph main-column">
      <div class="progress-bar">
        <div class="bar-segment documents-analyzed" style="width: 10%;">10%</div>
      </div>
      <div class="progress-legend">
        Documents Analyzed
      </div>
    </div>
  </div>
</section>
{% endblock %}

web/nuremberg/content/templates/content/trials.html
{% extends "base.html" %}
{% load static %}
{% block title %} Approaches to the Collection {% endblock %}
{% block body_class %}approaches{% endblock %}
{% block content %}
<br />

<div id="content"></div>
<section class="theme-white">
<div class="partial-width">
    <h1>The Thirteen Nuremberg Trials</h1>
    <p class="intro">
        Trial summaries, persons involved, transcript tables of contents
    </p>
</div>
</section>
<section class="theme-white">
        <p>The website currently presents information about the documents used in NMT
        Cases 1-4 and Case 7 (click on links).</p><br />
        <table class="table-trial-chronology">
          <tr>
            <td>IMT</td>
            <td>Major War Criminals (USA, France, UK, and USSR<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v. Hermann Goering et al. 1945-46)</td>
          </tr>
          <tr>
            <td>NMT 1</td>
            <td><a href="{% url 'content:nmt_1_intro' %}">Medical Case (USA v. Karl Brandt et al. 1946-47)</a></td>
          </tr>
          <tr>
            <td>NMT 2</td>
            <td><a href="{% url 'content:nmt_2_intro' %}">Milch Case (USA v. Erhard Milch 1946-47)</a></td>
          </tr>
          <tr>
            <td>NMT 3</td>
            <td><a href="{% url 'content:nmt_3_intro' %}">Justice Case (USA v. Josef Altstoetter et al. 1947)</a></td>
          </tr>
          <tr>
            <td>NMT 4</td>
            <td><a href="{% url 'content:nmt_4_intro' %}">Pohl Case (USA v. Oswald Pohl et al. 1947)</a></td>
          </tr>
          <tr>
            <td>NMT 5</td>
            <td>Flick Case (USA v. Friedrich Flick et al. 1947)</td>
          </tr>
          <tr>
            <td>NMT 6</td>
            <td>I. G. Farben (USA v. Carl Krauch et al. 1947-48)</td>
          </tr>
          <tr>
            <td>NMT 7</td>
            <td><a href="{% url 'content:nmt_7_intro' %}">Hostage Case (USA v. Wilhelm List et al. 1947-48)</a></td>
          </tr>
          <tr>
            <td>NMT 8</td>
            <td>RuSHA Case (USA v. Ulrich Greifelt et al. 1947-48)</td>
          </tr>
          <tr>
            <td>NMT 9</td>
            <td>Einsatzgruppen Case (USA v. Otto Ohlendorf et al. 1947-48)</td>
          </tr>
          <tr>
            <td>NMT 10</td>
            <td>Krupp Case (USA v. Alfred Krupp et al. 1947-48)</td>
          </tr>
          <tr>
            <td>NMT 11</td>
            <td>Ministries Case (USA v. Ernst von Weizsaecker et al. 1947-49)</td>
          </tr>
          <tr>
            <td>NMT 12</td>
            <td>High Command Case (USA v. Wilhelm von Leeb et al. 1947-48)</td>
          </tr>
        </table>
</section>
{% endblock %}