web/nuremberg/core/urls.py
from django.conf import settings
from django.conf.urls import include, url, re_path
from django.contrib import admin
from proxy.views import proxy_view
from django.views.generic.base import RedirectView
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from proxy.views import proxy_view

@csrf_exempt
def proxied(base_url):
    def proxy_handler(request, path):
    	remoteurl = base_url + path
    	return proxy_view(request, remoteurl)
    return proxy_handler

urlpatterns = [
    # re_path(r'^admin/', admin.site.urls),
    re_path(r'^transcripts/', include('nuremberg.transcripts.urls')),
    re_path(r'^documents/', include('nuremberg.documents.urls')),
    re_path(r'^photographs/', include('nuremberg.photographs.urls')),
    re_path(r'^search/', include('nuremberg.search.urls')),
    re_path(r'^', include('nuremberg.content.urls')),
    re_path(r'^proxy_image/printing/(?P<path>.*)$',
        # RedirectView.as_view(url='http://nuremberg.law.harvard.edu/imagedir/HLSL_NUR_printing/%(url)s')),
        proxied(base_url=settings.DOCUMENTS_PRINTING_URL)),
    re_path(r'^proxy_image/(?P<path>.*)$',
        # RedirectView.as_view(url='http://s3.amazonaws.com/nuremberg-documents/%(url)s'))
        proxied(base_url=settings.DOCUMENTS_URL), name='proxy_image'),
    re_path(r'^proxy_transcript/(?P<path>.*)$',
        proxied(base_url=settings.TRANSCRIPTS_URL), name='proxy_transcript'),
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /search/\n\nUser-agent: SiteimproveBot\nDisallow: /\n\nUser-agent: SiteimproveBot-Crawler\nDisallow: /", content_type="text/plain")),
]

handler400 = 'nuremberg.core.views.handler400'
handler403 = 'nuremberg.core.views.handler403'
handler404 = 'nuremberg.core.views.handler404'
handler500 = 'nuremberg.core.views.handler500'

web/nuremberg/search/urls.py
from django.conf.urls import include, url, re_path
from . import views

app_name = 'search'
urlpatterns = [
    # re_path(r'$', views.Search.as_view(), name='search'),
    re_path(r'$', views.Search.as_view(), name='search')
]

web/nuremberg/transcripts/urls.py
from django.conf.urls import url, re_path
from . import views

app_name = 'transcripts'
urlpatterns = [
    re_path(r'^(?P<transcript_id>\d+)-(?P<slug>[\-\w]+)?/search$', views.Search.as_view(), name='search'),
    re_path(r'^(?P<transcript_id>\d+)[^/]*/search$', views.Search.as_view()),
    re_path(r'^(?P<transcript_id>\d+)-(?P<slug>[\-\w]+)?$', views.Show.as_view(), name='show'),
    re_path(r'^(?P<transcript_id>\d+)][^/]*$', views.Show.as_view(), name='show'),

]

web/nuremberg/transcripts/models.py
import re
from io import BytesIO
from lxml import etree
from datetime import datetime
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from django.utils.functional import cached_property

from django.db import models
from nuremberg.documents.models import DocumentCase, DocumentActivity
from .xml import TranscriptPageJoiner

class Transcript(models.Model):
    case = models.OneToOneField(DocumentCase, related_name='transcript', on_delete=models.PROTECT)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    activities = models.ManyToManyField(DocumentActivity, related_name='transcripts')

    def slug(self):
        return slugify(self.title)

    def clamp_seq(self, seq):
        return min(max(seq, 1), self.total_pages)

    @cached_property
    def total_pages(self):
        return self.pages.count()

    def dates(self):
        return self.pages.order_by().values_list('date', flat=True).distinct()

    def get_seq_from_page_date(self, page_date, seq_number):
        # find the seq number for provided date
        # assume dates are valid since they come from selection
        page_date = datetime.strptime(page_date, '%Y-%m-%d')
        page = self.pages.filter(date=page_date).order_by('seq_number').first()
        if page:
            return page.seq_number
        return seq_number

    def get_seq_from_page_number(self, page_number, seq_number):
        # find the seq number for provided page number
        # we have to be a bit tricky because page numbers can repeat
        page = self.pages.filter(page_number=page_number).extra(select={'distance': "ABS(seq_number - %s)"}, select_params=(seq_number,), order_by=('distance',)).first()
        if page:
            return page.seq_number
        else:
            # guesstimate
            page = self.pages.filter(page_number__lte=page_number).order_by('-page_number').first()
            if page:
                return page.seq_number + (page_number - page.page_number)

        return seq_number

class TranscriptVolume(models.Model):
    transcript = models.ForeignKey(Transcript, related_name='volumes', on_delete=models.PROTECT)

    volume_number = models.IntegerField()
    description = models.TextField(blank=True, null=True)

# class TranscriptPageQuerySet(models.QuerySet):
#     use_for_related_fields = True
#     def joined_text(self):
#         joiner = TranscriptPageJoiner(self.all())
#         return joiner.html()

class TranscriptPage(models.Model):
    # objects = TranscriptPageQuerySet.as_manager()

    transcript = models.ForeignKey(Transcript, related_name='pages', on_delete=models.PROTECT)
    volume = models.ForeignKey(TranscriptVolume, related_name='pages', on_delete=models.PROTECT)
    updated_at = models.DateTimeField(auto_now=True)

    seq_number = models.IntegerField(db_index=True)
    volume_seq_number = models.IntegerField(db_index=True)

    date = models.DateTimeField(db_index=True, blank=True, null=True)
    page_number = models.IntegerField(blank=True, null=True)
    page_label = models.CharField(max_length=10, blank=True, null=True)

    image_url = models.TextField(blank=True, null=True)

    xml = models.TextField()

    def __getattribute__(self, attrname):
        orig = super().__getattribute__(attrname)
        if attrname == 'image_url' and settings.PROXY_TRANSCRIPTS:
            return reverse('proxy_transcript', kwargs={'path': orig.split('/')[-1]})
        return orig

    def xml_tree(self):
        return etree.fromstring(self.xml.encode('utf8'))

    def populate_from_xml(self):
        for event, element in etree.iterwalk(self.xml_tree()):
            if event != 'end':
                continue
            if element.tag == 'seqNo':
                self.seq_number = int(element.text)
            elif element.tag == 'sessionDate':
                try:
                    self.date = datetime.strptime(element.get('n'), '%Y-%m-%d')
                except:
                    self.date = None
            elif element.tag == 'pageNum':
                self.page_label = element.get('n')
                page_int = re.sub(r'[^\d]', '', self.page_label)
                if page_int:
                    self.page_number = int(page_int)
                else:
                    self.page_number = None

    def text(self):
        # TODO: this blob won't allow exact phrase matches across transcript pages.
        # It might be extended a few words into either adjacent page to allow that.
        text = ''
        for event, element in etree.iterwalk(self.xml_tree(), events=('start', 'end')):
            if element.tag == 'p' :
                if len(element) and element[0].tag == 'runningHead':
                    continue
                if event == 'start':
                    if element.text:
                        if len(element.text) < 20 and TranscriptPageJoiner.ignore_p.match(element.text):
                            continue
                        text += element.text
                else:
                    text += '\n\n'
            elif event == 'end' and element.tag == 'spkr':
                if element.text:
                    text += '<span class="speaker">{}</span> '.format(element.text)
                if element.tail: text += element.tail
            elif event == 'end' and element.tag in ('evidenceFileDoc', 'exhibitDocDef', 'exhibitDocPros'):
                if element.text: text += element.text
                if element.tail: text += element.tail
        return text

    def extract_evidence_codes(self):
        codes = []
        for event, element in etree.iterwalk(self.xml_tree()):
            if element.tag == 'evidenceFileDoc':
                codes.append(element.get('n'))
        return codes

    def extract_exhibit_codes(self):
        codes = []
        for event, element in etree.iterwalk(self.xml_tree()):
            if element.tag == 'exhibitDocPros':
                codes.append('Prosecution {}'.format(element.get('n')))
            elif element.tag == 'exhibitDocDef':
                codes.append('{} {}'.format(element.get('def') or 'Unknown Defendant', element.get('n')))
        return codes

    class Meta:
        unique_together = (
                ('transcript', 'seq_number'),
                ('volume', 'volume_seq_number')
            )
        index_together = (
                ('transcript', 'seq_number'),
                ('transcript', 'page_number'),
                ('transcript', 'date'),
                ('volume', 'volume_seq_number')
            )

web/nuremberg/search/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from haystack.generic_views import SearchView, FacetedSearchView, FacetedSearchMixin
from nuremberg.documents.models import Document
from .forms import DocumentSearchForm
from .lib.digg_paginator import DiggPaginator
from .lib.solr_grouping_backend import GroupedSearchQuerySet

class Search(FacetedSearchView):
    """
    This is a subclass of the default Haystack faceted search view to implement
    our modifications, including pagination, shorter query parameters, custom
    sorting, and labeled facets.

    You can add a search facet to the list simply by placing it in `facet_labels`.

    See `forms.py` for the faceting and fielded search logic itself.
    """
    load_all = False
    queryset = GroupedSearchQuerySet()

    # page numbers like [1, 2 ... 6, 7, 8, 9, 10, ... 19, 20]
    paginator_class = DiggPaginator
    paginate_by = 15
    context_pages = 4
    edge_pages = 2

    form_class = DocumentSearchForm
    search_field = 'q'
    filter_field = 'f'
    material_field = 'm'
    sort_field = 'sort'
    default_sort = 'relevance'

    facet_labels = (
        ('Material Type', 'material_type'),
        ('Trial', 'case_names'),
        ('Defendant', 'defendants'),
        ('Date', 'date_year'),
        ('Author', 'authors'),
        ('Language', 'language'),
        ('Source', 'source'),
        ('Trial Issues', 'trial_activities'),
    )
    facet_to_label = {field: label for (label, field) in facet_labels}
    facet_fields = [label[1] for label in facet_labels]

    def get(self, *args, **kwargs):
        try:
            return super().get(*args, **kwargs)
        except Http404:
            if self.request.GET.get('page', 1) == 1:
                raise
        params = self.request.GET.copy()
        del params['page']
        return redirect('%s?%s' % (self.request.path, params.urlencode()))

    def form_invalid(self, form):
        # override SearchView to give a blank search by default
        # TODO: this seems unnecessary
        self.queryset = form.search()
        context = self.get_context_data(**{
            self.form_name: form,
            'object_list': self.get_queryset()
        })
        return self.render_to_response(context)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'sort_results': self.request.GET.get(self.sort_field, self.default_sort),
            'selected_facets': self.request.GET.getlist(self.filter_field),
            'facet_to_label': self.facet_to_label
        })
        return kwargs

    def get_queryset(self):
        # override FacetedSearchMixin
        qs = super(FacetedSearchMixin, self).get_queryset()
        for field in self.facet_fields:
            sort = 'count'
            qs = qs.facet(field, missing=True, sort=sort, mincount=1)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # pull the query out of form so it is pre-processed
        context['query'] = context['form'].data.get('q') or '*'
        if context['facets']:
            labeled_facets = []
            for (label, field) in self.facet_labels:
                counts = context['facets']['fields'].get(field, [])
                # missing ignores mincount and sorting
                if (None, 0) in counts:
                    counts.remove((None, 0))
                else:
                    pass
                    # sort missing into the other facet values
                    # counts.sort(key=lambda field: field[1], reverse=True)
                labeled_facets.append({
                    'field': field,
                    'label': label,
                    'counts': counts
                })
            context.update({'labeled_facets': labeled_facets})

        if context['form']:
            context['facet_lookup'] = {}
            for (field, value, facet) in context['form'].applied_filters:
                context['facet_lookup'][facet] = True

        if self.request.GET.get('partial'):
            context['base_template'] = 'search/partial.html'
        else:
            context['base_template'] = None

        return context

    def get_paginator(self, *args, **kwargs):
        return self.paginator_class(*args, body=self.context_pages, tail=self.edge_pages, **kwargs)

web/nuremberg/transcripts/views.py
from datetime import datetime
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http.response import JsonResponse
from django.views.generic import View
from nuremberg.search.views import Search as GenericSearchView
from .models import Transcript
from .xml import TranscriptPageJoiner
import json

class Search(GenericSearchView):
    template_name = 'transcripts/search.html'

    paginate_by = 10
    default_sort = 'page'

    def get(self, request, transcript_id, *args, **kwargs):
        self.transcript = Transcript.objects.get(id=transcript_id)
        return super().get(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'transcript_id': self.transcript.id
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'transcript': self.transcript,
            'show_search_bar': True
        })
        return context

class Show(View):
    template_name = 'transcripts/show.html'
    page_alignment = 10

    def get(self, request, transcript_id, *args, **kwargs):
        transcript = Transcript.objects.get(id=transcript_id)
        total_pages = transcript.total_pages

        seq_number = int(request.GET.get('seq', 1))
        page_number = int(request.GET.get('page', 0))
        if page_number:
            seq_number = transcript.get_seq_from_page_number(page_number, seq_number)

        page_date = request.GET.get('date')
        if page_date:
            seq_number = transcript.get_seq_from_page_date(page_date, seq_number)

        from_seq, to_seq = self.get_request_seq_range(request, seq_number)

        from_seq = transcript.clamp_seq(from_seq)
        to_seq = transcript.clamp_seq(to_seq)

        pages = transcript.pages.filter(seq_number__gte=from_seq, seq_number__lte=to_seq).all()
        joiner = TranscriptPageJoiner(pages, include_first=from_seq == 1, include_last=to_seq == total_pages)
        joiner.build_html()

        if request.GET.get('partial'):
            return JsonResponse({'html': render_to_string('transcripts/joined_pages.html', {'pages':joiner.html_pages}), 'from_seq': joiner.from_seq, 'to_seq': joiner.to_seq, 'seq': seq_number})

        current_page = next(page for page in pages if page.seq_number == seq_number)
        return render(request, self.template_name, {
            'transcript': transcript,
            'joiner': joiner,
            'seq': seq_number,
            'total_pages': total_pages,
            'dates': transcript.dates(),
            'current_page': current_page,
            'query': request.GET.get('q'),
            'page_obj': None,
            'show_search_bar': False
            })

    def get_request_seq_range(self, request, seq_number):
        # so that page ranges are generally cacheable, we align initial page loads to 10-page strides, plus 1
        # e.g. requesting seq=10, 13, or 19 will get you pages 1 - 30 inclusive,
        # so all future range requests will be aligned to 31 - 40 and so on.
        from_seq = int(request.GET.get('from_seq', (seq_number // self.page_alignment) * self.page_alignment - self.page_alignment))
        to_seq = int(request.GET.get('to_seq', (seq_number // self.page_alignment) * self.page_alignment + self.page_alignment + 1))

        return (from_seq, to_seq)

web/nuremberg/transcripts/templates/transcripts/base.html
{% extends "base.html" %}
{% load search_url static cache %}

{% block title %} Transcript Viewer - {{transcript.title}} {% endblock %}

{% block content %}
<section class="theme-light flush">
  {% block document_tools %}
    {% if query or show_search_bar %}
      <div class="document-tools">
        <form class="document-search-inline" method='GET' action={% url 'transcripts:search' transcript_id=transcript.id slug=transcript.slug %}>
          {% include 'search/search-bar.html' %}
          {% if page_obj %}
            <label><strong>{{ paginator.count }}</strong> page{{ paginator.count|pluralize }} with results</label>
            <a href="{% sort_results 'page' %}" {% if form.sort_results == 'page' %}class="active"{% endif %}>Order by Page</a>
            <a href="{% sort_results 'relevance' %}" {% if form.sort_results == 'relevance' %}class="active"{% endif %}>Order by Relevance</a>
          {% endif %}
        </form>
        <div class="return-link">
          <a href="{% search_url query %}"> &larr; Back to all results </a>
        </div>
      </div>
      <hr />
    {% endif %}
    {% block document-nav %}
      <div class="document-tools">
        {% block document_controls %}
        {% endblock %}
        <div class="page-buttons">
          {% block page_selection %}
          {% endblock %}
          <button class="first-page">
            First Page
          </button>
          <button class="prev-page">
            Previous Page
          </button>
          <button class="next-page">
            Next Page
          </button>
          <button class="last-page">
            Last Page
          </button>
        </div>
      </div>
      <hr />
    {% endblock %}
  {% endblock %}
  <div class="sidebar-layout">
    <div class="sidebar-column document-info">
      {% block document_info %}

      {% endblock %}
    </div>
    <div id="content"></div>
    <div id="document-viewport" class="main-column">
      <div class="viewport-content">
        {% block viewport %}
        {% endblock %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

web/nuremberg/transcripts/templates/transcripts/joined_pages.html
{% load humanize %}
{% for row in pages %}
  {% with page=row.page html=row.html %}
    <div class="page"  data-seq="{{ page.seq_number }}" data-page="{{ page.page_number|default:"" }}" data-date="{{ page.date|date:'Y-m-d'}}">
      <div class="page-handle">
          <span class="page-details">
              HLSL Seq. No. {{ page.seq_number }}
              {% if page.date %}
                  - {{ page.date|date:'d F Y' }}
              {% endif %}
              {% if page.image_url %}
                  <span class="image-options">
                      - Image
                      [<a class='view-image'>View</a>]
                      [<a class='download-image' href="{{ page.image_url }}" download="Transcript Seq {{ page.seq_number }}.jpg">Download</a>]
                  </span>
              {% endif %}
          </span>
          <span class="page-number">Page {{ page.page_label|default:"Unlabeled"|intcomma }}</span>
      </div>

      {{ html|safe }}
    </div>
  {% endwith %}
{% endfor %}

web/nuremberg/transcripts/templates/transcripts/search.html
{% extends "transcripts/show.html" %}
{% load search_url %}

{% block title %} Search in Transcript - {{transcript.title}} {% endblock %}

{% block javascript_module %}transcript-search{% endblock %}
{% block body_class %}transcript-search{% endblock %}
{% block document-nav %}{% endblock %}

{% block viewport %}
  <div class="search-results">
    {% for result in page_obj.object_list %}
      <div class="result-row">
        <a class="teaser" href="{% url 'transcripts:show' transcript_id=result.transcript_id slug=result.slug %}?seq={{ result.seq_number }}&amp;q={% encode_string query|default:'' %}">Page {{result.page_label|default:"Unlabeled"}} </a>
        {% if result.highlighted %}<div class="occurrence-count">{{ result.highlighted.highlight|length }} occurrence{{ result.highlighted.highlight|length|pluralize }}</div>{% endif %}
          <p>
            {% if result.highlighted %}
              {% for snippet in result.highlighted.highlight|slice:":2" %}
              <span class="ellipsis">[ ... ]</span>
                {{ snippet|trim_snippet }}
              {% endfor %}
            {% else %}
              {{ result.text|slice:":150"|trim_snippet }}
            {% endif %}
            <span class="ellipsis">[ ... ]</span>
          </p>
      </div>
    {% empty %}
      <p>
        No results found in this transcript.
      </p>
      <p>
        <a href="{% search_query query %}">Click here to search for "{{query}}" in all documents.</a>
      </p>
    {% endfor %}
  </div>
  {% include 'search/pagination.html' %}
{% endblock %}

{% block print_controls %}
{% endblock %}

web/nuremberg/transcripts/templates/transcripts/show.html
{% extends "transcripts/base.html" %}
{% load search_url %}
{% block title %} Transcript Viewer - {{transcript.title}} {% endblock %}

{% block body_class %}transcript-viewer{% endblock %}
t
{% block javascript_module %}transcript-viewer{% endblock %}

{% block document_controls %}
  <div class="zoom-buttons pull-left">
    <form action="" method="GET">
      <input type="hidden" name="seq" value="{{ seq }}" />
      <select title="Jump to date" name="date" class="select-date">
        {% for date in dates %}
          <option value="{{ date|date:'Y-m-d' }}" {% if date == current_page.date %}selected{% endif %}>{{ date|date:'d F Y' }}</option>
        {% endfor %}
      </select>
      <button class="go-button">Go to date</button>
    </form>
  </div>
{% endblock %}
{% block tools_overlay %}{% endblock %}

{% block page_selection %}
  <form class="go-to-page" action="" method="GET">
    <input type="hidden" name="seq" value="{{ seq }}" />
    <label>
      Go to page:
      <input type="number" name="page" value="{{ current_page.page_number|default:"" }}"/>
    </label>
    <button class="go-button">Go</button>
  </form>
{% endblock %}

{% block viewport %}
  <div class="transcript-controls above">
    <div class="end-indicator">
      <noscript>
        <a href="?seq={{ seq|add:"-10" }}">Previous Pages</a>
      </noscript>
    </div>
  </div>
  <div class="transcript-text" data-total-pages="{{ total_pages }}" data-seq="{{ seq }}" data-from-seq="{{ joiner.from_seq }}" data-to-seq="{{ joiner.to_seq }}">
    {% with joiner.html_pages as pages %}
      {% include 'transcripts/joined_pages.html' %}
    {% endwith %}
  </div>
  <div class="transcript-controls below">
    <div class="end-indicator">
        <noscript>
          <a href="?seq={{ seq|add:"10" }}">Next Pages</a>
        </noscript>
      </div>
  </div>
{% endblock %}

{% block document_info %}
  <div class="material-icon small material-documents"></div>
  <p class="trial-flags">
      <span class="trial-flag trial-{{transcript.case.tag_name|slugify}}">{{transcript.case.tag_name}}</span>
    &nbsp;
  </p>

  {% block print_controls %}
    <div class="print-controls">
      <button class="print-document">Print</button>
      <form class="print-options hide">
        Next
        <input type="number" title="number of pages to print" class="page-range" name="pages" value="20" min="1" max="20"/>
        pages
        <button class="do-print">Print</button>
      </form>
      <div class="print-loading hide">Downloading pages to print... <span class="progress"></span></div>
    </div>
  {% endblock %}

  <h1 class="h3">{{transcript.title}}</h1>
  <p class="module">{{transcript.description}}</p>
  <div class="print-show"></div>
  {% with transcript.activities.all as activities %}
  {% if activities %}
    <h2 class="h6">Trial Issue{{activities|length|pluralize}}</h2>
    <p>
      {% for activity in activities %}
          <a class="tag-button" href="{% search_query issue=activity.short_name %}">{{activity.short_name}}</a>
      {% endfor %}
    </p>
  {% endif %}
  {% endwith %}
  {% with transcript.case.defendants.all as defendants %}
  {% if defendants %}
    <h2 class="h6">Defendant{{defendants|length|pluralize}}</h2>
    <p>
      {% for defendant in defendants %}
          <a href="{% search_query defendant=defendant.full_name %}">{{defendant.full_name}}</a>{% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
  {% endif %}
  {% endwith %}
{% endblock %}